import type {
  CommunityExternalLink,
  CommunityMetadata,
} from "./types";

export const COMMUNITY_SCHEMA_VERSION = 1 as const;
export const COMMUNITY_LIMITS = {
  nameBytes: 64,
  symbolBytes: 12,
  uriBytes: 256,
  descriptionBytes: 2_000,
  linkLabelBytes: 32,
  externalLinks: 10,
} as const;

export const GOVERNANCE_LIMITS = {
  votingDelay: { min: 1, max: 4_294_967_295 },
  votingPeriod: { min: 2, max: 4_294_967_295 },
  proposalThreshold: {
    min: BigInt(1),
    max: (BigInt(1) << BigInt(128)) - BigInt(1),
  },
  quorum: {
    min: BigInt(1),
    max: (BigInt(1) << BigInt(128)) - BigInt(1),
  },
} as const;

export type GovernanceDraft = {
  proposalThreshold: string;
  quorum: string;
  votingDelay: string;
  votingPeriod: string;
};

export type GovernanceDraftErrors = Partial<
  Record<keyof GovernanceDraft, string>
>;

export const DEFAULT_GOVERNANCE_DRAFT: GovernanceDraft = {
  proposalThreshold: "1",
  quorum: "1",
  votingDelay: "1",
  votingPeriod: "10000",
};

/**
 * Authoring draft: what the creator types in the wizard. It deliberately has
 * no URI strings. Collection and metadata URIs, and the metadata hash, are
 * generated by Stolla when the review step pins the documents; see
 * `CommunityDeploymentPayload`.
 */
export type CommunityMetadataDraft = {
  name: string;
  symbol: string;
  description: string;
  externalLinkLabel: string;
  externalLinkUrl: string;
};

export type CommunityMetadataDraftErrors = Partial<
  Record<keyof CommunityMetadataDraft, string>
>;

/**
 * Deployment payload: the generated values the CommunityFactory invocation
 * needs. It exists only after the pin pipeline succeeds and is validated
 * immediately before simulate/deploy. It is never typed by a user.
 */
export type CommunityDeploymentPayload = {
  collectionUri: string;
  metadataUri: string;
  /** Lowercase hex SHA-256 of the pinned community document bytes. */
  metadataHash: string;
  logoUri?: string;
};

export type CommunityDeploymentPayloadErrors = Partial<
  Record<keyof CommunityDeploymentPayload, string>
>;

const textEncoder = new TextEncoder();

export function utf8Length(value: string): number {
  return textEncoder.encode(value).length;
}

function hasControlCharacter(value: string): boolean {
  return /[\u0000-\u001f\u007f]/.test(value);
}

export function isResourceUri(value: string): boolean {
  if (utf8Length(value) > COMMUNITY_LIMITS.uriBytes) return false;
  if (value.startsWith("ipfs://")) return value.length > "ipfs://".length;
  if (!value.startsWith("https://")) return false;

  try {
    return Boolean(new URL(value).hostname);
  } catch {
    return false;
  }
}

export function isHttpsUrl(value: string): boolean {
  if (utf8Length(value) > COMMUNITY_LIMITS.uriBytes) return false;
  try {
    const url = new URL(value);
    return url.protocol === "https:" && Boolean(url.hostname);
  } catch {
    return false;
  }
}

export function resolveCommunityResourceUrl(uri: string): string {
  if (uri.startsWith("https://")) return uri;
  if (uri.startsWith("ipfs://") && uri.length > "ipfs://".length) {
    const gateway =
      process.env.NEXT_PUBLIC_IPFS_GATEWAY_URL ?? "https://ipfs.io/ipfs/";
    return `${gateway.replace(/\/?$/, "/")}${uri.slice("ipfs://".length)}`;
  }
  throw new Error("The resource URI is not a supported public URI.");
}

export function validateAuthoringDraft(
  draft: CommunityMetadataDraft,
): CommunityMetadataDraftErrors {
  const errors: CommunityMetadataDraftErrors = {};
  const name = draft.name.trim();
  const description = draft.description.trim();

  if (!name) {
    errors.name = "Enter a community name.";
  } else if (
    utf8Length(draft.name) > COMMUNITY_LIMITS.nameBytes ||
    hasControlCharacter(draft.name)
  ) {
    errors.name = "Use at most 64 UTF-8 bytes and no control characters.";
  }

  if (!draft.symbol.trim()) {
    errors.symbol = "Enter a collection symbol.";
  } else if (
    utf8Length(draft.symbol) > COMMUNITY_LIMITS.symbolBytes ||
    !/^[A-Z0-9]+$/.test(draft.symbol)
  ) {
    errors.symbol = "Use 1–12 uppercase letters or numbers.";
  }

  if (!description) {
    errors.description = "Enter a public community description.";
  } else if (utf8Length(draft.description) > COMMUNITY_LIMITS.descriptionBytes) {
    errors.description = "Use at most 2,000 UTF-8 bytes.";
  }

  const hasLinkLabel = Boolean(draft.externalLinkLabel.trim());
  const hasLinkUrl = Boolean(draft.externalLinkUrl.trim());
  if (hasLinkLabel || hasLinkUrl) {
    if (!hasLinkLabel) {
      errors.externalLinkLabel = "Enter a label for this link.";
    } else if (
      utf8Length(draft.externalLinkLabel) >
        COMMUNITY_LIMITS.linkLabelBytes ||
      hasControlCharacter(draft.externalLinkLabel)
    ) {
      errors.externalLinkLabel =
        "Use at most 32 UTF-8 bytes and no control characters.";
    }

    if (!hasLinkUrl) {
      errors.externalLinkUrl = "Enter the HTTPS link URL.";
    } else if (!isHttpsUrl(draft.externalLinkUrl)) {
      errors.externalLinkUrl =
        "Use a valid https:// URL of at most 256 bytes.";
    }
  }

  return errors;
}

const ZERO_HASH = "0".repeat(64);

export function isMetadataHashHex(value: string): boolean {
  return /^[0-9a-f]{64}$/.test(value) && value !== ZERO_HASH;
}

/**
 * Fails closed: a payload is only valid when the pin pipeline produced both
 * URIs and a non-zero 32-byte hash. Called right before simulate/deploy so a
 * stale or missing pipeline result can never reach the factory.
 */
export function validateDeploymentPayload(
  payload: CommunityDeploymentPayload | null | undefined,
): CommunityDeploymentPayloadErrors {
  const errors: CommunityDeploymentPayloadErrors = {};
  if (!payload) {
    return {
      collectionUri: "Pin the metadata documents before deploying.",
      metadataUri: "Pin the metadata documents before deploying.",
      metadataHash: "Pin the metadata documents before deploying.",
    };
  }
  if (!payload.collectionUri || !isResourceUri(payload.collectionUri)) {
    errors.collectionUri = "The generated collection URI is missing or invalid.";
  }
  if (!payload.metadataUri || !isResourceUri(payload.metadataUri)) {
    errors.metadataUri = "The generated metadata URI is missing or invalid.";
  }
  if (!isMetadataHashHex(payload.metadataHash)) {
    errors.metadataHash =
      "The metadata hash must be a non-zero 32-byte SHA-256 digest.";
  }
  if (payload.logoUri !== undefined && !isResourceUri(payload.logoUri)) {
    errors.logoUri = "The generated logo URI is invalid.";
  }
  return errors;
}

function parseUnsignedInteger(value: string): bigint | null {
  const trimmed = value.trim();
  if (!/^\d+$/.test(trimmed)) return null;
  try {
    return BigInt(trimmed);
  } catch {
    return null;
  }
}

export function validateGovernanceDraft(
  draft: GovernanceDraft,
): GovernanceDraftErrors {
  const errors: GovernanceDraftErrors = {};
  const proposalThreshold = parseUnsignedInteger(draft.proposalThreshold);
  const quorum = parseUnsignedInteger(draft.quorum);
  const votingDelay = parseUnsignedInteger(draft.votingDelay);
  const votingPeriod = parseUnsignedInteger(draft.votingPeriod);

  if (
    proposalThreshold === null ||
    proposalThreshold < GOVERNANCE_LIMITS.proposalThreshold.min ||
    proposalThreshold > GOVERNANCE_LIMITS.proposalThreshold.max
  ) {
    errors.proposalThreshold =
      "Enter a whole number from 1 through the maximum u128 value.";
  }
  if (
    quorum === null ||
    quorum < GOVERNANCE_LIMITS.quorum.min ||
    quorum > GOVERNANCE_LIMITS.quorum.max
  ) {
    errors.quorum =
      "Enter a whole number from 1 through the maximum u128 value.";
  }
  if (
    votingDelay === null ||
    votingDelay < BigInt(GOVERNANCE_LIMITS.votingDelay.min) ||
    votingDelay > BigInt(GOVERNANCE_LIMITS.votingDelay.max)
  ) {
    errors.votingDelay = "Enter a whole number from 1 through 4,294,967,295 ledgers.";
  }
  if (
    votingPeriod === null ||
    votingPeriod < BigInt(GOVERNANCE_LIMITS.votingPeriod.min) ||
    votingPeriod > BigInt(GOVERNANCE_LIMITS.votingPeriod.max)
  ) {
    errors.votingPeriod = "Enter a whole number from 2 through 4,294,967,295 ledgers.";
  } else if (votingDelay !== null && votingPeriod <= votingDelay) {
    errors.votingPeriod =
      "Voting period must be greater than the voting delay.";
  }

  return errors;
}

function parseExternalLinks(value: unknown): CommunityExternalLink[] | null {
  if (value === undefined) return [];
  if (!Array.isArray(value) || value.length > COMMUNITY_LIMITS.externalLinks) {
    return null;
  }

  const links: CommunityExternalLink[] = [];
  for (const link of value) {
    if (
      !isPlainObject(link) ||
      !hasOnlyKeys(link, ["label", "url"]) ||
      typeof link.label !== "string" ||
      !link.label ||
      utf8Length(link.label) > COMMUNITY_LIMITS.linkLabelBytes ||
      hasControlCharacter(link.label) ||
      typeof link.url !== "string" ||
      !isHttpsUrl(link.url)
    ) {
      return null;
    }
    links.push({ label: link.label, url: link.url });
  }
  return links;
}

export function parseCommunityMetadata(
  input: unknown,
  expectedContracts?: { nftContract: string; governorContract: string },
): CommunityMetadata | null {
  if (
    !isPlainObject(input) ||
    !hasOnlyKeys(input, [
      "schemaVersion",
      "name",
      "description",
      "logo",
      "externalLinks",
      "nftContract",
      "governorContract",
    ]) ||
    input.schemaVersion !== COMMUNITY_SCHEMA_VERSION ||
    typeof input.name !== "string" ||
    !input.name.trim() ||
    utf8Length(input.name) > COMMUNITY_LIMITS.nameBytes ||
    hasControlCharacter(input.name) ||
    typeof input.description !== "string" ||
    !input.description.trim() ||
    utf8Length(input.description) > COMMUNITY_LIMITS.descriptionBytes
  ) {
    return null;
  }

  if (
    input.logo !== undefined &&
    (typeof input.logo !== "string" || !isResourceUri(input.logo))
  ) {
    return null;
  }

  if (
    input.nftContract !== undefined &&
    (typeof input.nftContract !== "string" ||
      input.nftContract !== expectedContracts?.nftContract)
  ) {
    return null;
  }
  if (
    input.governorContract !== undefined &&
    (typeof input.governorContract !== "string" ||
      input.governorContract !== expectedContracts?.governorContract)
  ) {
    return null;
  }

  const externalLinks = parseExternalLinks(input.externalLinks);
  if (externalLinks === null) return null;

  return {
    schemaVersion: COMMUNITY_SCHEMA_VERSION,
    name: input.name,
    description: input.description,
    ...(typeof input.logo === "string" ? { logo: input.logo } : {}),
    externalLinks,
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(
  value: Record<string, unknown>,
  allowed: readonly string[],
): boolean {
  return Object.keys(value).every((key) => allowed.includes(key));
}
